# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: indexfinger
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link_to_index_base
    - index_base_to_middle
    - index_middle_to_end
    - base_link_to_middle_base
    - middle_base_to_middle
    - middle_middle_to_end
    - base_link_to_pinky_base
    - pinky_base_to_middle
    - pinky_middle_to_end
    - base_link_to_ring_base
    - ring_base_to_middle
    - ring_middle_to_end
    - thumb_base_palm
    - thumb_end_to_thumb_base
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: indexfinger_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link_to_index_base
      - index_base_to_middle
      - index_middle_to_end
  - name: middlefinger_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link_to_middle_base
      - middle_base_to_middle
      - middle_middle_to_end
  - name: ringfinger_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link_to_ring_base
      - ring_base_to_middle
      - ring_middle_to_end
  - name: thumbfinger_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - thumb_base_palm
      - thumb_end_to_thumb_base
  - name: pinkyfinger_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_link_to_pinky_base
      - pinky_base_to_middle
      - pinky_middle_to_end